# Use official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy project files
COPY . .

# Expose the backend port
EXPOSE 5000

# Start the backend server
CMD ["node", "--watch", "server.js"]
